blog/urls.py
from django.urls import path,re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),    # /blog/
    path('post/', views.PostLV.as_view(), name='post_index'),    # /blog/post/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),   # /blog/post/django-example/
    path('archive/', views.PostAV.as_view(), name='post_archive'),   # /blog/archive   --7
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),  # /blog/archive/2019/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),  # /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'), # /blog/archive/2019/nov/10/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'), # /blog/archive/today/
]

bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkLV,BookmarkDV

app_name = 'bookmark'
urlpatterns = [
    path('',BookmarkLV.as_view(),name = 'index'),
    path('<int:pk>/',BookmarkDV.as_view(),name = 'detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from mysite.views import HomeView
# from bookmark.views import BookmarkLV, BookmarkDV
# from django.views.generic import ListView,DetailView
# from bookmark.models import Bookmark
urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/',include('bookmark.urls')),
    path('blog/',include('blog.urls')),
    path('',HomeView.as_view(), name='home')
    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),

    #urls with definition

    # path('bookmark/', ListView.as_view(model=Bookmark), name='index'),
    # path('bookmark/<int:pk>/', DetailView.as_view(model=Bookmark), name='detail'),
]

blog/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE',max_length=50)
    slug = models.SlugField('SLUG',unique=True,allow_unicode=True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION',max_length=100,blank=True,help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

# Create your models here.

bookmark/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    date = models.DateTimeField('date',default=timezone.now, null = True, blank = True)

    def __str__(self):
        return self.title
        # return "%s %s" %(self.title, self.url)
# Create your models here.

polls/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
# Create your views here.
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post


# create your views here.

# ---List view
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


# ---Detail view
class PostDV(DetailView):
    model = Post


# ---Archive View
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

bookmark/views.py
from django.shortcuts import render
from bookmark.models import Bookmark
from django.views.generic import ListView, DetailView

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark
# Create your views here.

mysite/views.py
from django.views.generic import TemplateView

#--- TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'

polls/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}

<h1>Blog List</h1>
<br>

{% for post in posts %}
    <h3><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h3>
    {{ post.modify_dt|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

<br>
<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page= {{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>
</div>

{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}

<h1>Post Archive until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year{{ date|date:"-Y" }}</a></li>
    {% endfor %}
</ul>
<br/>
<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a> </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}

<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}

<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}

<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F"}}</a>
    </li>
    {% endfor %}
</ul>
<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}

<h2>{{ object.title }}</h2>

<p>
    {% if object.get_previous %}
    <a href="{{ object.get_previous.get_absolute_url }}" tilte="View previous post">
        &laquo;-- {{ object.get_previous }}
    </a>
    {% endif %}

    {% if object.get_next %}
    | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
    {{ object.get_next }} --&raquo;
    </a>
    {% endif %}
</p>

<p>{{ objcet.modify_dt|date:"j F Y" }}</p>
<br>

<div>
    {{ object.content|linebreaks }}
</div>

{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}bookmark_detail.html{% endblock %}

{% block content %}
    <h1>{{ object_title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}bookmark_list.html{% endblock %}

{% block content %}

    <h1>Bookmark List</h1>

    <br>

    <ul>
        {% for bookmark in object_list %}
        <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    {% block extra-style %}{% endblock %}
</head>
<body style="padding-top:90px;">
<nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django Web Programming</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item mx-1 btn btn-light">
          <a class="nav-link text-info" href="{% url 'home' %}">Home</a></li>
        <li class="nav-item mx-1 btn btn-light">
          <a class="nav-link text-info" href="{% url 'bookmark:index' %}">Bookmark</a></li>
        <li class="nav-item mx-1 btn btn-light">
          <a class="nav-link text-info" href="{% url 'blog:index' %}">Blog</a></li>
        <li class="nav-item mx-1 btn btn-light">
            <a class="nav-link text-info" href="">Photo</a></li>
         <li class="nav-item dropdown mx-1 btn btn-light">
             <a class="nav-link dropdown[toggle text-info"href="#" data-toggle="dropdown">Util</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
            <a class="dropdown-item" href="">Search</a>
          </div>
        </li>
      </ul>

      <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/c998a172fe.js"></script>
{% block extra-script %}{% endblock %}
</body>
</html>

templates/home.html
<!---
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Django Web Programming</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
            Dropdown
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>

<div class="container bg-warning">
    <h4>This is CONTENT area.</h4>
</div>
<footer class="fixed-bottom bg-info">
    <h4>This is FOOTER area.</h4>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>
!--->


{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/gold.png' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 30%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}

.title {
    color: #c0;
    font-weight: bold;
}

.powered {
    position: relative;
    top: 77%;
    color: #c0;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
<div class="home-image">
    <h2 class="title">장고 웹 프로그래밍</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i>powered by django and bootstrap.</h4>
</div>

<hr style="margin: 10px 0;">

<div class="row text-center">
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p>Bookmark is a Uniform Resource Identifier (URL)
        that is stored for later retrieval in any of various storage format.
        You can store your own bookmarks by Bookmark application.
        It's also possible to update or delete your bookmarks.</p>
    </div>
    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p>This application makes it possible to log daily events or write your own interest such as hobbies, techniques, etc.
            A typical blog combines text, digital images, and links to other blogs, web pages, and other media related to its topic.
        </p>
    </div>
</div>

{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by shkim</div>
</footer>
{% endblock %}